name: Pull Request
on: [pull_request]
jobs:
    PullRequest:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Make dynamic env_file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_POSTGRES_USER: "postgres"
                  envkey_POSTGRES_PASSWORD: "postgres"
                  envkey_POSTGRES_DB: "students_tests"
                  envkey_DATABASE_URL: "postgresql://postgres:postgres@database_github-ci:5432/students_tests"
                  directory: back-end/
                  file_name: .env.test
            - name: Run tests
              run: docker-compose -f docker-compose-tests.yml run node_github-ci npm run test
